### ISSUE TITLE
Use SonarQube for local dev env

### ISSUE THREAD

**Issue by rapostolovici** [rapostolovici/helpmate-hub-be#17]
Use a sonarqube docker container for local dev environment.

**Comment by sebiTCR** [comment]
To use Sonarqube in a local dev environment, do the following:
1. Make sure you have docker installed.
2. Download SonarQube's image for docker (docker pull sonarqube)
3. Use the following command to run it :
```
docker run --name sonarQube -p 9000:9000 -p 9092:9092 sonarqube
```
4. sonarQube is now working, but we need to analyze a project first. Open a terminal in the project's root folder and run 
```
mvn sonar:sonar -Dsonar.host.url=http://localhost:9000
```
5.  Now wait until the code has been analyzed by SonarQube, and then open localhost:9000 in your browser
6. Congrats! Now sonarQube has analyzed your code and you can see what issues you have in your code
